version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://cache
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      # - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped
    expose:
      - 6379